<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $QRCode = $this->record($this->driver)->getQRCode('core');
    $coverUrls = $this->driver->getCoverDetails();
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'large', $coverUrls['cover_backlink_url']);
    $cover = $coverDetails['html'];
    $coverSize = $coverDetails['size'];
    $preview = $this->record($this->driver)->getPreviews();
  ?>
  <div class="media-body">

    <h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <?php if ($current['label'] == 'Language'): ?>
            <?php
              $languages = explode("<br />", $current['value']);
              foreach ($languages as $index => $language):
                $languages[$index] = $this->transEsc($language);
              endforeach;
            ?>
            <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=implode("<br />", $languages)?></td></tr>
          <?php else: ?>
            <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
          <?php endif; ?>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
  <?php if ($QRCode || $cover || $preview): ?>
    <div class="media-right <?=$this->escapeHtmlAttr($coverSize)?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
        <?php if ($coverUrls['toc_url']): ?>
          <a href="<?=$this->escapeHtmlAttr($coverUrls['toc_backlink_url'])?>" data-failover-href="<?=$this->escapeHtmlAttr($coverUrls['toc_failover_backlink_url']); ?>" target="_blank">
            <img alt="<?=$this->transEsc('Table of Contents')?>" src="<?=$this->escapeHtmlAttr($coverUrls['toc_url']); ?>" data-failover-src="<?=$this->escapeHtmlAttr($coverUrls['toc_failover_url']); ?>" onerror="this.onerror = null; this.src = this.getAttribute('data-failover-src'); this.parentNode.href = this.parentNode.getAttribute('data-failover-href');"/>
          </a>
        <?php endif; ?>
        <?php if ($coverUrls['cover_backlink_url']): ?>
          <a href="<?=$this->escapeHtmlAttr($coverUrls['cover_backlink_url'])?>" target="_blank"><?=$this->transEsc('muni::Open ObalkyKnih')?></a>
        <?php endif; ?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
</div>
