<?php
$source = [];
$fields = $this->driver->getMarcRecord()->getFields("773");
if (!is_array($fields)) {
  return $encodings;
}
foreach ($fields as $currentField) {
  $allSubfields = $currentField->getSubfields();
  if (!empty($allSubfields)) {
    foreach ($allSubfields as $currentSubfield) {
      if (!in_array($currentSubfield->getCode(), ['q', '0', '9', 'w'])) {
        $data = trim($currentSubfield->getData());
        if (!empty($data)) {
          $source[] = $this->escapeHtml($data);
        }
      }
    }
  }
}
?>
<?php if (!empty($source)): ?>
  <?=implode("<br />", $source)?>
<?php endif; ?>
