<?php
$encodings = [];
$fields = $this->driver->getMarcRecord()->getFields("347");
if (!is_array($fields)) {
  return $encodings;
}
foreach ($fields as $currentField) {
  $allSubfields = $currentField->getSubfields();
  if (!empty($allSubfields)) {
    foreach ($allSubfields as $currentSubfield) {
      if (in_array($currentSubfield->getCode(), ['b'])) {
        $data = trim($currentSubfield->getData());
        if (!empty($data)) {
          $encodings[] = $this->escapeHtml($data);
        }
      }
    }
  }
}
?>
<?php if (!empty($encodings)): ?>
  <?=implode("<br />", $encodings)?>
<?php endif; ?>
