<?php
  $sources = [];
  foreach ($this->driver->getSources() as $source):
    $title = '<a href="/Record/' . $source['id'] . '">' . $this->escapeHtml($source['text']) . "</a>";
    $details = [$title];
    foreach ($raw_source['details'] as $detail):
      $details[] = $this->escapeHtml($detail);
    endforeach;
    $sources[] = implode("<br />", $details);
  endforeach;
?>
<?=implode("<br /><br />", $sources)?>
