<div class="inner-but-full-line"></div>
<footer class="hidden-print">
    <div class="footer-container">
        <div class="footer-column">
            <p><strong><?= $this->transEsc('Search Options') ?></strong></p>
            <ul>
                <li><a href="<?= $this->url('search-history') ?>"><?= $this->transEsc('Search History') ?></a></li>
                <li><a href="<?= $this->url('search-advanced') ?>"><?= $this->transEsc('Advanced Search') ?></a></li>
            </ul>
        </div>
        <div class="footer-column">
            <p><strong><?= $this->transEsc('Find More') ?></strong></p>
            <ul>
                <li><a href="<?= $this->url('browse-home') ?>"><?= $this->transEsc('Browse the Catalog') ?></a></li>
                <li><a href="<?= $this->url('alphabrowse-home') ?>"><?= $this->transEsc('Browse Alphabetically') ?></a></li>
                <li><a href="<?= $this->url('channels-home') ?>"><?= $this->transEsc('channel_explore') ?></a></li>
                <li><a href="<?= $this->url('search-reserves') ?>"><?= $this->transEsc('Course Reserves') ?></a></li>
                <li><a href="<?= $this->url('search-newitem') ?>"><?= $this->transEsc('New Items') ?></a></li>
            </ul>
        </div>
        <div class="footer-column">
            <p><strong><?= $this->transEsc('Need Help?') ?></strong></p>
            <ul>
                <li><a href="<?= $this->url('help-home') ?>?topic=search&amp;_=<?= time() ?>" data-lightbox class="help-link"><?= $this->transEsc('Search Tips') ?></a></li>
                <li><a href="<?= $this->url('content-page', ['page' => 'asklibrary']) ?>"><?= $this->transEsc('Ask a Librarian') ?></a></li>
                <li><a href="<?= $this->url('content-page', ['page' => 'faq']) ?>"><?= $this->transEsc('FAQs') ?></a></li>
            </ul>
        </div>
    </div>
    <div class="poweredby">
        <?= $this->layout()->poweredBy ?>
    </div>

    <div class="row footer-row">
        <div class="col-xs-6 col-sm-6 col-md-6 footer-col">

            <div class="mu-copyright" style="margin-top: 1rem;">
                &copy;&nbsp;2019&nbsp;Masarykova&nbsp;univerzita<br/>
                <a href="mailto:kic_admins@ics.muni.cz">Správce stránek</a>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-5 footer-col">
            <p class="text-right" style="margin-top: 1rem;">
                Provozováno a vyvíjeno<br />
                <a href="https://www.ics.muni.cz/" target="_blank">
                    Ústavem výpočetní techniky Masarykovy&nbsp;univerzity
                </a>
            </p>
        </div>
        <div class="hidden-xs hidden-sm col-md-1">
            <img class="media-object" style="width: 78px; height: 60px" src="<?= $this->url('home') ?>themes/muni/images/UVT-lg-eng-rgb.png" alt="ÚVT MU" />
        </div>

        <!--
        <div class="col-xs-6 hidden-md hidden-lg">
            <p class="footer-uvt-sm">
                Provozováno a vyvíjeno <a href="https://www.ics.muni.cz/" target="_blank">Ústavem&nbsp;výpočetní&nbsp;techniky&nbsp;MU
                </a>
            </p>
        </div>
        -->
    </div>
</footer>
