<div class="inner-but-full-line"></div>
<footer class="hidden-print">
    <div class="footer-container">
        <div class="footer-column">
            <p><strong><?= $this->transEsc('Search Options') ?></strong></p>
            <ul>
                <li><a href="<?= $this->url('search-history') ?>"><?= $this->transEsc('Search History') ?></a></li>
                <li><a href="<?= $this->url('alphabrowse-home') ?>"><?= $this->transEsc('Browse Alphabetically') ?></a></li>
                <li><a href="<?= $this->url('search-newitem') ?>"><?= $this->transEsc('New Items') ?></a></li>
            </ul>
        </div>
        <div class="footer-column">
            <p><strong><?= $this->transEsc('Find More') ?></strong></p>
            <ul>
                <li><a href="https://ezdroje.muni.cz/"><?= $this->transEsc('muni::EIZ Portal') ?></a></li>
                <li><a href="https://discovery.muni.cz/"><?= $this->transEsc('muni::Discovery') ?></a></li>
                <li><a href="https://is.muni.cz/thesis/"><?= $this->transEsc('muni::Thesis') ?></a></li>
                <li><a href="https://www.muni.cz/spoluprace/sluzby/knihovny"><?= $this->transEsc('muni::Libraries') ?></a></li>
            </ul>
        </div>
        <div class="footer-column">
            <p><strong><?= $this->transEsc('Need Help?') ?></strong></p>
            <ul>
                <li><a href="<?= $this->url('help-home') ?>?topic=search&amp;_=<?= time() ?>" data-lightbox class="help-link"><?= $this->transEsc('Search Tips') ?></a></li>
                <!-- <li><a href="<?= $this->url('content-page', ['page' => 'faq']) ?>"><?= $this->transEsc('FAQs') ?></a></li> -->
                <li><a href="https://inet.muni.cz/app/knihovny/prihlaska"><?= $this->transEsc('muni::Service Agreement') ?></a></li>
            </ul>
        </div>
    </div>
    <div class="poweredby">
        <?= $this->layout()->poweredBy ?>
    </div>

    <div class="row footer-row">
        <div class="col-xs-6 col-sm-6 col-md-6 footer-col">

            <div class="mu-copyright" style="margin-top: 1rem;">
                &copy;&nbsp;2019&nbsp;<?= $this->transEsc('muni::masaryk') ?>&nbsp;<?= $this->transEsc('muni::university') ?>
                <br/>
                <span class="email" data-text="<?= $this->transEsc('muni::contact') ?>">kic_admins<img src="<?= $this->url('home') ?>themes/muni/images/zavinac.gif" alt=" zavinac | at " />ics<img src="<?= $this->url('home') ?>themes/muni/images/tecka.gif" alt=" tecka | dot " />muni<img src="<?= $this->url('home') ?>themes/muni/images/tecka.gif" alt=" tecka | dot " />cz</span>
                <?php $this->headScript()->appendFile("email.js"); ?>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-5 footer-col">
            <p class="text-right" style="margin-top: 1rem;">
                <?= $this->transEsc('muni::powered_by') ?><br />
                <a href="https://www.ics.muni.cz/" target="_blank">
                    <?= $this->transEsc('muni::ics7p') ?> <?= $this->transEsc('muni::masaryk7p') ?>&nbsp;<?= $this->transEsc('muni::university7p') ?>
                </a>
            </p>
        </div>
        <div class="hidden-xs hidden-sm col-md-1">
            <img class="media-object" style="width: 78px; height: 60px" 
                 src="<?= $this->url('home') ?>themes/muni/images/UVT-lg-eng-rgb.png" 
                 alt="<?= $this->transEsc('muni::ics_logo_desc') ?>" />
        </div>

        <!--
        <div class="col-xs-6 hidden-md hidden-lg">
            <p class="footer-uvt-sm">
                Provozováno a vyvíjeno <a href="https://www.ics.muni.cz/" target="_blank">Ústavem&nbsp;výpočetní&nbsp;techniky&nbsp;MU
                </a>
            </p>
        </div>
        -->
    </div>
</footer>
