<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = ['holdings' => []];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
				<?=$this->transEsc("muni::ils_login_pretext")?>
        <a href="<?=$this->url('myresearch-userlogin')?>"><?=$this->transEsc("muni::ils_login_link")?></a>.
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<?php endif; ?>
  <?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
      <div class="item-internet-links">
          <h3><?= $this->transEsc("Internet") ?></h3>
          <?php if (!empty($urls)): ?>
              <?php foreach ($urls as $current): ?>
                  <a href="<?= $this->escapeHtmlAttr($this->proxyUrl($current['url'])) ?>"><?= $this->escapeHtml($current['desc']) ?></a><br/>
              <?php endforeach; ?>
          <?php endif; ?>
          <?php if ($openUrlActive): ?><?= $openUrl->renderTemplate() ?><?php endif; ?>
          <?php if ($doiActive): ?><?= $doi->renderTemplate() ?><?php endif; ?>
      </div>
  <?php endif; ?>

<?php $this->headScript()->appendFile("eprez.js"); ?>
<div id="eprez"></div>
<script>eprez_tag("<?=$this->driver->getUniqueID()?>");</script>

<div id="item-filters" class="hidden"></div>

<?php
    $locationHoldings = [];
    foreach ($holdings['holdings'] as $holding):
        foreach ($holding['items'] as $item):
            $location = $item['location'];
            if (!array_key_exists($location, $locationHoldings)):
                $locationHoldings[$location] = [];
            endif;
            $locationHoldings[$location][] = $item;
        endforeach;
    endforeach;
    $holdingCount = count($locationHoldings, COUNT_RECURSIVE);
?>
<?php foreach ($locationHoldings as $location => $items): ?>
  <?php $locationText = $this->transEsc('location_' . $location, [], $location); ?>
  <?php if (count($locationHoldings) > 1 && $holdingCount > 10): ?>
    <h3 id="items-<?=$location?>" class="items-location">
      <a href="#items-<?=$location?>"><?=$locationText?></a>
    </h3>
  <?php endif; ?>
  <table class="table items">
    <tr>
      <th><?=$this->transEsc("Description")?></th>
      <th><?=$this->transEsc("Status")?></th>
      <th class="th-library"><?=$this->transEsc("Library")?></th>
      <th><?=$this->transEsc("Collection")?></th>
      <th><?=$this->transEsc("Call Number")?></th>
      <th><?=$this->transEsc("Holdings_notes")?></th>
      <th><?=$this->transEsc("Barcode")?></th>
    </tr>
    <?php foreach ($items as $item): ?>
      <tr data-location="<?=$locationText?>"
      <?php if (!empty($item['year'])): ?>
        data-year="<?=$item['year']?>"
      <?php endif; ?>
      <?php if (!empty($item['volume'])): ?>
        data-volume="<?=$item['volume']?>"
      <?php endif; ?>
      >
        <td label-title="<?=$this->transEsc("Description")?>:">
          <?php if (isset($item['description'])): ?>
            <?=$item['description']?>
          <?php endif; ?>
        </td>
        <td label-title="<?=$this->transEsc("Status")?>:">
          <?php
              try {
                  echo $this->context($this)->renderInContext(
                      'RecordTab/holdingsils/' . $this->tab->getTemplate() . '.phtml',
                      ['holding' => $item]
                  );
              } catch (Exception $e) {
                  echo $this->context($this)->renderInContext(
                      'RecordTab/holdingsils/standard.phtml',
                      ['holding' => $item]
                  );
              }
          ?>
        </td>
        <td class="library" label-title="<?=$this->transEsc("Library")?>:">
          <?php if (isset($item['locationhref']) && $item['locationhref']): ?>
            <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
          <?php else: ?>
            <?=$locationText?>
          <?php endif; ?>
        </td>
        <td class="collection" label-title="<?=$this->transEsc("Collection")?>:">
          <?php if (isset($item['collection'])): ?>
            <?=$item['collection']?>
          <?php endif; ?>
        </td>
        <td class="call_number" label-title="<?=$this->transEsc("Call Number")?>:">
          <?php $callNo = $item['callnumber']; ?>
          <?php if ($this->callnumberHandler): ?>
            <a href="<?=$this->url('alphabitemse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
          <?php else: ?>
            <?=$this->escapeHtml($callNo)?>
          <?php endif; ?>
        </td>
        <td label-title="<?=$this->transEsc("Holdings_notes")?>:">
          <?php if (isset($item['notes'])): foreach ($item['notes'] as $note): ?>
            <?=$this->escapeHtml($note)?><br/>
          <?php endforeach; endif; ?>
        </td>
        <td class="barcode" label-title="<?=$this->transEsc("Barcode")?>:">
          <?php if (isset($item['barcode'])): ?>
            <?=$item['barcode']?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endforeach; ?>
<table class="table items hidden" id="filtered-item-table">
    <tr>
      <th><?=$this->transEsc("Description")?></th>
      <th><?=$this->transEsc("Status")?></th>
      <th class="th-library"><?=$this->transEsc("Library")?></th>
      <th><?=$this->transEsc("Collection")?></th>
      <th><?=$this->transEsc("Call Number")?></th>
      <th><?=$this->transEsc("Holdings_notes")?></th>
      <th><?=$this->transEsc("Barcode")?></th>
    </tr>
</table>
<?php $this->headScript()->appendFile("datafieldslinks-" . $this->layout()->userLang . ".js"); ?>
<?php $this->headScript()->appendFile("datafieldslinks.js"); ?>
<?php $alephLanguages = ['cs' => 'cze', 'en' => 'eng']; ?>
<?php $userLang = array_key_exists($this->layout()->userLang, $alephLanguages) ? $this->layout()->userLang : 'en'; ?>
<?php $alephLang = $alephLanguages[$userLang]; ?>
<script>showItemLocations('<?=$alephLang?>');</script>
<script>showItemLinks('<?=$alephLang?>', '<?=$this->driver->getUniqueID()?>');</script>
<script>showItemFilters('<?=$this->driver->getUniqueID()?>');</script>

<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
