<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = ['holdings' => []];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
				<?=$this->transEsc("muni::ils_login_pretext")?>
        <a href="<?=$this->url('myresearch-userlogin')?>"><?=$this->transEsc("muni::ils_login_link")?></a>.
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<?php endif; ?>
<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><?php endif; ?>
  <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
<?php endif; ?>

<table class="table table-view">
  <tr>
    <th><?=$this->transEsc("Call Number")?></th>
    <th><?=$this->transEsc("Barcode")?></th>
    <th><?=$this->transEsc("Status")?></th>
    <th><?=$this->transEsc("Library")?></th>
    <th><?=$this->transEsc("Holdings_notes")?></th>
  </tr>
  <?php foreach ($holdings['holdings'] ?? [] as $holding): ?>
    <?php foreach ($holding['items'] as $item): ?>
      <tr>
        <td>
          <?php $callNo = $item['callnumber']; ?>
          <?php if ($this->callnumberHandler): ?>
            <a href="<?=$this->url('alphabitemse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
          <?php else: ?>
            <?=$this->escapeHtml($callNo)?>
          <?php endif; ?>
        </td>
        <td>
          <?php if (isset($item['barcode'])): ?>
            <?=$item['barcode']?>
          <?php endif; ?>
        </td>
        <td>
          <?php
              try {
                  echo $this->context($this)->renderInContext(
                      'RecordTab/holdingsils/' . $this->tab->getTemplate() . '.phtml',
                      ['holding' => $item]
                  );
              } catch (Exception $e) {
                  echo $this->context($this)->renderInContext(
                      'RecordTab/holdingsils/standard.phtml',
                      ['holding' => $item]
                  );
              }
          ?>
        </td>
        <td>
          <?php $locationText = $this->transEsc('location_' . $item['location'], [], $item['location']); ?>
          <?php if (isset($item['locationhref']) && $item['locationhref']): ?>
            <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
          <?php else: ?>
            <?=$locationText?>
          <?php endif; ?>
        </td>
        <td>
          <?php if (isset($item['notes'])): foreach ($item['notes'] as $note): ?>
            <?=$this->escapeHtml($note)?><br/>
          <?php endforeach; endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  <?php endforeach; ?>
</table>

<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
