<?php
    $data = $this->recommend->getRecommendations();
    $results = $this->recommend->getResults();
    $displayQuery = $results->getParams()->getDisplayQuery();
    $that = $this;
    $callback = function ($heading) use ($results, $displayQuery, $that) {
        // Generate a new search URL that replaces the user's current term
        // with the authority term:
        $url = $that->url($results->getOptions()->getSearchAction())
            . $results->getUrlQuery()->replaceTerm($displayQuery, $heading);
        return "<a href=\"$url\">" . $that->escapeHtml($heading) . '</a>';
    };

    $useforLimit = 25;
    if (isset($data['usefor'])):
      $data['usefor'] = array_map($callback, $data['usefor']);
      if (count($data['usefor']) > $useforLimit):
        $data['usefor'] = array_slice($data['usefor'], 0, $useforLimit - 1);
        $data['usefor'][] = '…';
      endif;
      $usefor = implode(', ', $data['usefor']);
    else:
      $usefor = [];
    endif;

    $seealsoLimit = 25;
    if (isset($data['seealso'])):
      $data['seealso'] = array_map($callback, $data['seealso']);
      if (count($data['seealso']) > $seealsoLimit):
        $data['seealso'] = array_slice($data['seealso'], 0, $seealsoLimit - 1);
        $data['seealso'][] = '…';
      endif;
      $seealso = implode(', ', $data['seealso']);
    else:
      $seealso = [];
    endif;
?>
<?php if (!empty($usefor)): ?>
  <div class="authoritybox">
    <div><strong><?=$this->transEsc('muni::Use for')?>:</strong></div>
    <div><?=$usefor?></div>
  </div>
<?php endif; ?>
<?php if (!empty($seealso)): ?>
  <div class="authoritybox">
    <div><strong><?=$this->transEsc('See also')?>:</strong></div>
    <div><?=$seealso?></div>
  </div>
<?php endif; ?>
