<?php
    $data = $this->recommend->getRecommendations();
    $results = $this->recommend->getResults();
    $displayQuery = $results->getParams()->getDisplayQuery();
    $that = $this;
    $callback = function ($heading) use ($results, $displayQuery, $that) {
        // Generate a new search URL that replaces the user's current term
        // with the authority term:
        $url = $that->url($results->getOptions()->getSearchAction())
            . $results->getUrlQuery()->replaceTerm($displayQuery, $heading);
        return "<a href=\"$url\">" . $that->escapeHtml($heading) . '</a>';
    };

    // Remove duplicate seealso headings:
    if (isset($data['usefor']) and isset($data['seealso'])):
      $seeAlsoValueDict = [];
      foreach ($data['seealso'] as $heading):
        $seeAlsoValueDict[$heading] = true;
      endforeach;

      $useForValues = [];
      foreach ($data['usefor'] as $heading):
        if (!isset($seeAlsoValueDict[$heading])):
          $useForValues[] = $heading;
        endif;
      endforeach;

      $data['usefor'] = $useForValues;
    endif;

    $limits = ['usefor' => 25, 'seealso' => 25];
    $labels = ['usefor' => 'muni::Use for', 'seealso' => 'See also'];
    $content = [];
    foreach ($data as $key => $headings):
      if (isset($labels[$key])):
        $headings = array_map($callback, $headings);
        if (isset($limits[$key]) && count($headings) > $limits[$key]):
          $headings = array_slice($headings, 0, $limits[$key] - 1);
          $headings[] = '…';
        endif;
        if (!empty($headings)):
?>
          <div class="authoritybox">
            <div><strong><?=$this->transEsc($labels[$key])?>:</strong></div>
            <div><?=implode(', ', $headings)?></div>
          </div>
<?php
        endif;
      endif;
    endforeach;
?>
